apiVersion: webservices.cern.ch/v1alpha1
kind: OidcReturnURI
metadata:
  name: etl-hybrid-bbqc-oauth2-callback
  labels:
    app: etl-hybrid-bbqc
spec:
  redirectURI: https://etl-hybrid-bbqc.app.cern.ch/oauth2/callback
