apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl-hybrid-bbqc-comments
  labels:
    app: etl-hybrid-bbqc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
