apiVersion: apps/v1
kind: Deployment
metadata:
  name: etroc-solder-inspection
  labels:
    app: etroc-solder-inspection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etroc-solder-inspection
  template:
    metadata:
      labels:
        app: etroc-solder-inspection
    spec:
      containers:
        - name: web
          image: image-registry.openshift-image-registry.svc:5000/etroc-solder-inspection/etroc-solder-inspection:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
